const fs = require('fs');

const content = `# 🚔 CitySense Backend (Node.js + Google Gemini)

## 📝 Project Overview
**CitySense** is an AI-powered infrastructure monitoring system. 
This backend handles data ingestion from the Python ML model, serves detection data to the Frontend, and uses **Google Gemini 2.5** to generate smart maintenance reports.

## ✅ Status: 🟢 ONLINE
- **Server Port:** 5000
- **Database:** Local JSON (Mock Data)
- **AI Service:** Google Gemini 2.5 Flash

---

## 🔑 Setup Instructions (For Teammates)

1. **Install Dependencies**
   \`npm install\`

2. **Configure Environment**
   Create a file named \`.env\` in the root folder.
   **Ask Abhiram for the actual keys** and paste them like this:
   
   GEMINI_API_KEY=AIzaSy...
   GOOGLE_MAPS_API_KEY=AIzaSy...

3. **Start the Server**
   \`node server.js\`
   *Server runs at:* http://localhost:5000

---

## 🗺️ Frontend Integration (Google Maps)
To use the Map in the React Frontend, add this script to your index.html (inside the <head> tag):

<script 
  src="https://maps.googleapis.com/maps/api/js?key=YOUR_GOOGLE_MAPS_KEY_HERE&callback=initMap"
  async defer>
</script>
*(Replace YOUR_GOOGLE_MAPS_KEY_HERE with the key from the .env file)*

---

## 📡 API Endpoints

### 1. Get Map Data (For Frontend Map)
* **Method:** GET
* **URL:** http://localhost:5000/api/detections
* **Response:** JSON list of potholes, garbage, and risk scores.

### 2. Generate Smart Report (For Dashboard)
* **Method:** POST
* **URL:** http://localhost:5000/api/generate-report
* **Body:** { "detections": [...] }
* **Response:** Text summary generated by Google Gemini.

### 3. Upload Live Data (For ML/Python Team)
* **Method:** POST
* **URL:** http://localhost:5000/api/update-live-data
* **Body:** JSON object of new detections.

---

## ⚠️ Known Issues
* **Google Maps Watermark:** You may see a "For Development Purposes Only" watermark on the map. This is expected (Developer Mode) and the map is still fully functional. **Do not worry about it.**
`;

fs.writeFileSync('README.md', content);
console.log("✅ README.md created successfully!");